# this workflow runs when a release was published.
on:
  release:
    types: [published]

name: "release_published"
jobs:
  # Build the binary using GoReleaser
  build_binary:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v2.4.0
      -
        name: Get go.mod details
        uses: Eun/go-mod-details@v1.0.4
        id: go-mod-details
      -
        name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ steps.go-mod-details.outputs.go_version }}
      -
        name: Login to Docker Registry
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: GoReleaser
        uses: goreleaser/goreleaser-action@v2.8.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
